apiVersion: v1
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "postgresadmin"
  DB_TYPE: "postgres"
  DB_NAME: "wikidb"
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: wiki-js
---
